import type { SourceDefinition } from "../types/content.ts";

export const OFFICIAL_SOURCES: SourceDefinition[] = [
  {
    id: "openai-newsroom",
    name: "OpenAI Newsroom",
    kind: "official_site",
    adapter: "rss",
    channelUrl: "https://openai.com/newsroom/",
    fetchUrl: "https://openai.com/news/rss.xml",
    laneHint: "daily",
  },
  {
    id: "anthropic-news",
    name: "Anthropic News",
    kind: "official_site",
    adapter: "web_page",
    channelUrl: "https://www.anthropic.com/news",
    laneHint: "daily",
    urlIncludes: ["/news/"],
    urlExcludes: ["/news$"],
  },
  {
    id: "anthropic-research",
    name: "Anthropic Research",
    kind: "official_blog",
    adapter: "web_page",
    channelUrl: "https://www.anthropic.com/research",
    laneHint: "daily",
    urlIncludes: ["/research/"],
    urlExcludes: ["/research$"],
  },
  {
    id: "google-deepmind-blog",
    name: "Google DeepMind Blog",
    kind: "official_blog",
    adapter: "web_page",
    channelUrl: "https://deepmind.google/blog/",
    laneHint: "daily",
    urlIncludes: ["/blog/"],
    urlExcludes: ["/blog/"],
  },
  {
    id: "microsoft-research-blog",
    name: "Microsoft Research Blog",
    kind: "official_blog",
    adapter: "rss",
    channelUrl: "https://www.microsoft.com/en-us/research/blog/",
    fetchUrl: "https://www.microsoft.com/en-us/research/feed/",
    laneHint: "daily",
  },
  {
    id: "meta-newsroom",
    name: "Meta Newsroom",
    kind: "official_site",
    adapter: "rss",
    channelUrl: "https://about.fb.com/news/",
    fetchUrl: "https://about.fb.com/news/feed/",
    laneHint: "daily",
  },
  {
    id: "huggingface-blog",
    name: "Hugging Face Blog",
    kind: "official_blog",
    adapter: "rss",
    channelUrl: "https://huggingface.co/blog",
    fetchUrl: "https://huggingface.co/blog/feed.xml",
    laneHint: "daily",
  },
  {
    id: "nist-ai",
    name: "NIST AI",
    kind: "regulator",
    adapter: "web_page",
    channelUrl: "https://www.nist.gov/artificial-intelligence",
    laneHint: "daily",
    urlIncludes: ["/news-events/"],
  },
  {
    id: "eu-ai-office",
    name: "EU AI Office",
    kind: "regulator",
    adapter: "web_page",
    channelUrl: "https://digital-strategy.ec.europa.eu/en/policies/ai-office",
    laneHint: "daily",
    urlIncludes: ["/news/"],
  },
];
